config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  resources :articles do
    member do
      post :notify_friend
    end
    resources :comments
  end
  resources :users
  resource :session
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :name, :email, :body, presence: true
  validate :article_should_be_published

  after_create :email_article_author

  def article_should_be_published
    errors.add(:article_id, I18n.t('comments.errors.not_published_yet')) if article && !article.published?
  end

  def email_article_author
    NotifierMailer.comment_added(self).deliver_later
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_article, except: :destroy
  before_action :authenticate, only: :destroy

  def create
    @comment = @article.comments.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @article, notice: t('comments.create_success') }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to @article, notice: t('comments.create_failure') }
        format.js { render :fail_create }
      end
    end
  end

  def destroy
    @article = current_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: t('comments.destroy_success') }
      format.js
    end
  end

  private
    def load_article
      @article = Article.find(params[:article_id])
    end

    def comment_params
      params.require(:comment).permit(:name, :email, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="<%= dom_id comment %>">
  <h3>
    <%= comment.name %> &lt;<%= comment.email %>&gt; <%= t("comments.said") %>:
    <% if @article.owned_by? current_user %>
      <span class="actions">
        <%= link_to t("general.delete"), article_comment_path(article_id: @article, id: comment), confirm: t("general.are_you_sure"), method: :delete, remote: true %>
      </span>
    <% end %>
  </h3>
  <%= comment.body %>
</div>

app/views/comments/_new.html.erb
<%= form_with(model: @article.comments.new, url: article_comments_path(@article)) do |form| %>
  <div class="field">
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %><br />
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :body %><br />
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit t("comments.add") %>
  </div>
<% end %>

app/views/comments/create.js.erb
document.querySelector("#comments").insertAdjacentHTML("beforeend", "<%= escape_javascript render @comment %>");

document.querySelector("#main form").reset();

app/views/comments/destroy.js.erb
var comments = document.querySelector("#comments");
comments.removeChild(document.querySelector("#<%= dom_id @comment %>"));

app/views/comments/fail_create.js.erb
alert("<%= @comment.errors.full_messages.to_sentence.html_safe %>");

app/views/comments/new.js.erb
document.querySelector("#comments").insertAdjacentHTML("afterend", "<%= escape_javascript render partial: 'new' %>");

var comment_form = document.querySelector("main form");
comment_form.style.opacity = 0;
setTimeout(function() {
  comment_form.style.transition = 'opacity 1s';
  comment_form.style.opacity = 1;
}, 10);

document.querySelector("#new_comment_link").style.display = 'none'