config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  resources :articles do
    member do
      post :notify_friend
    end
    resources :comments
  end
  resources :users
  resource :session
  get "/login", to: "sessions#new", as: "login"
  get "/logout", to: "sessions#destroy", as: "logout"
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :body, presence: true

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments

  has_one_attached :cover_image
  attr_accessor :remove_cover_image
  after_save { cover_image.purge if remove_cover_image == '1' }
  after_save :broadcast_new_article

  has_rich_text :body

  scope :published, -> { where.not(published_at: nil) }
  scope :draft, -> { where(published_at: nil) }
  scope :recent, -> { where('articles.published_at > ?', 1.week.ago.to_date) }
  scope :where_title, -> (term) { where("articles.title LIKE ?", "%#{term}%") }

  def long_title
    "#{title} - #{published_at}"
  end

  def published?
    published_at.present?
  end

  def owned_by?(owner)
    return false unless owner.is_a?(User)
    user == owner
  end

  private

    def broadcast_new_article
      if published? && saved_change_to_published_at?
        ActionCable.server.broadcast(
          "articles:new",
          {
            new_article: ArticlesController.render(
              partial: 'articles/new_article_notification',
              locals: { article: self }
            )
          }
        )
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate, except: [:index, :show, :notify_friend]
  before_action :set_article, only: [:show, :notify_friend]
  before_action :set_users_article, only: [:edit, :update, :destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.includes(:user).with_rich_text_body.with_attached_cover_image.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @email_a_friend = EmailAFriend.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: t('articles.create_success') }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: t('articles.update_success') }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: t('articles.destroy_success') }
      format.json { head :no_content }
    end
  end

  def notify_friend
    @email_a_friend = EmailAFriend.new(email_a_friend_params)

    if @email_a_friend.valid?
      NotifierMailer.email_friend(@article, @email_a_friend.name, @email_a_friend.email).deliver_later
      redirect_to @article, notice: t('articles.notify_friend_success')
    else
      render :notify_friend, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def set_users_article
      @article = current_user.articles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :cover_image, :remove_cover_image, :location, :excerpt, :body, :published_at, category_ids: [])
    end

    def email_a_friend_params
      params.require(:email_a_friend).permit(:name, :email)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="article">
  <h3>
    <%= link_to article.title, article %>
    <% if article.owned_by? current_user %>
      <span class="actions">
        <%= link_to t('general.edit'), edit_article_path(article) %>
        <%= link_to t('general.delete'), article, confirm: t('general.are_you_sure'), method: :delete %>
      </span>
    <% end %>
  </h3>
  <hr>
  <% if article.cover_image.attached? %>
    <%= image_tag article.cover_image.variant(resize_to_limit: local_assigns.fetch(:cover_image_options, [200, 200])) %>
    <hr>
  <% end %>
  <%= article.body %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("errors.header", count: article.errors.count) %></h2>

      <ul>
        <% article.errors.full_message.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image %>

    <% if article.cover_image.attached? %>
      <p>
        <%= image_tag article.cover_image.variant(resize_to_limit: [50, 50]) %>
        <hr>
        <%= form.label :remove_cover_image do %>
          <%= form.check_box :remove_cover_image %> <%= t("articles.remove_this_image") %>
        <% end %>
      </p>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
      <% b.label { b.check_box + b.text } %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :excerpt %>
    <%= form.text_field :excerpt %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= submit_or_cancel(form) %>
  </div>
<% end %>

app/views/articles/_new_article_notification.html.erb
<div id="new-article-notification">
  <h3><%= t("articles.new_article_published") %></h3>

  <%= link_to article.title, article %>
</div>

app/views/articles/_notify_friend.html.erb
<%= form_with(model: @email_a_friend, url: notify_friend_article_path(article), id: 'email_a_friend') do |form| %>
  <% if @email_a_friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= t("errors.header", count: @email_a_friend.errors.count) %></h2>

      <ul>
        <% @email_a_friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, t('general.your_name') %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email, t("general.your_friend_email") %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit t("general.send_email") %> <%= t("general.or") %>
    <%= link_to t("general.cancel"), '#', onclick: "document.querySelector('#notify_friend').style.display='none';return false;" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1><%= t("articles.editing_article") %></h1>

<%= render 'form', article: @article %>

<%= link_to t("general.show"), @article %> |
<%= link_to t("general.back"), articles_path %>

app/views/articles/index.html.erb
<h1><%= t("articles.articles") %></h1>

<div id="articles">
  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<h1><%= t("articles.new_article") %></h1>

<p>
  <%= t("articles.draft_via_email_notice_html", mailto_link: mail_to(current_user.draft_article_email)) %>
</p>

<%= render 'form', article: @article %>

<%= link_to t("general.back"), articles_path %>

app/views/articles/notify_friend.js.erb
document.querySelector('#email_a_friend').innerHTML = "<%= escape_javascript render partial: 'notify_friend', locals: { article: @article } %>";

app/views/articles/show.html.erb
<%= render @article, locals: { cover_image_options: [500, 500] } %>

<%= link_to t("general.email_a_friend"), '#', onclick: "document.querySelector('#notify_friend').style.display = 'block'; return false;" %>

<div id="notify_friend" style="display: none">
  <%= render 'notify_friend', article: @article %>
</div>

<h3><%= t("comments.comments") %></h3>

<div id="comments">
  <%= render @article.comments %>
</div>

<%= link_to t("comments.new_comment"), new_article_comment_path(@article), remote: true, id: 'new_comment_link' %>